-- ------------------------------------------------------------
-- Entidade que armazena os Server Storage que são os Clientes (hosts) espalhados pelo rede interna e controlados pelo servidor MeshStorage, para envio dos arquivos para armazenamento.
-- ------------------------------------------------------------

CREATE TABLE TB_SERVER_STORAGE (
  ID_SERVER_STORAGE BIGINT NOT NULL AUTO_INCREMENT,
  ID_SERVER_STORAGE_CLIENT VARCHAR(100) NOT NULL,
  NM_SERVER_STORAGE VARCHAR(100) NOT NULL,
  NM_STORAGE_CLIENT VARCHAR(50) NOT NULL,
  CD_IP_SERVER_STORAGE VARCHAR(20) NOT NULL,
  DS_OS_SERVER_STORAGE VARCHAR(50) NOT NULL,
  QT_TOTAL_SPACE_STORAGE_CLIENT BIGINT NOT NULL,
  QT_FREE_SPACE_STORAGE_CLIENT BIGINT NOT NULL,
  QT_TOTAL_FILES_STORAGE_CLIENT BIGINT NOT NULL DEFAULT 0,
  IS_AVAILABLE_STORAGE_CLIENT BOOL NOT NULL DEFAULT false,
  DH_AVAILABLE_STORAGE_CLIENT DATETIME NULL,
  DH_REGISTERED_SERVER_STORAGE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID_SERVER_STORAGE)
);

-- ------------------------------------------------------------
-- Entidade que armazena as aplicações utilizadas no proceso de armazenamento de arquivos nos repositórios de arquivos (file server).
-- ------------------------------------------------------------

CREATE TABLE TB_APPICATION (
  ID_APPICATION BIGINT NOT NULL AUTO_INCREMENT,
  NM_APPLICATION VARCHAR(10) NOT NULL,
  DS_APPLICATION VARCHAR(500) NOT NULL,
  TX_ALLOWED_FILE_TYPES TEXT NOT NULL,
  QT_MAXIMUM_FILE_SIZE_MB BIGINT NOT NULL DEFAULT 2,
  IS_COMPRESSED_FILE_CONTENT_TOZIP BOOL NOT NULL DEFAULT true,
  IS_CONVERT_IMAGE_FILE_TOWEBP BOOL NOT NULL DEFAULT true,
  IS_APPLY_OCR_FILE_CONTENT BOOL NOT NULL DEFAULT false,
  IS_ALLOW_DUPLICATE_FILE BOOL NOT NULL DEFAULT true,
  QT_TOTAL_FILES_APPLICATION BIGINT NOT NULL DEFAULT 0,
  CD_STATUS_APPLICATION INTEGER UNSIGNED NOT NULL DEFAULT 1,
  DH_REGISTERED_APPLICATION DATETIME NOT NULL DEFAULT CURRENT_DATETIME,
  DH_REMOVED_APPLICATION DATETIME NULL,
  PRIMARY KEY(ID_APPICATION)
);

-- ------------------------------------------------------------
-- Entidade para armazenamento das informações do arquivo armazenado no repositório de arquivos.
-- ------------------------------------------------------------

CREATE TABLE TB_FILE_STORAGE (
  ID_FILE_STORAGE BIGINT NOT NULL AUTO_INCREMENT,
  ID_APPICATION BIGINT NOT NULL,
  CD_FILE_STORAGE_CLIENT VARCHAR(100) NOT NULL,
  ID_SERVER_STORAGE_CLIENT VARCHAR(100) NOT NULL,
  DS_APPLICATION_STORAGE_FOLDER VARCHAR(100) NOT NULL,
  NM_FILE_LOGIC VARCHAR(300) NOT NULL,
  NM_FILE_FISICAL VARCHAR(100) NOT NULL,
  DS_FILE_CONTENT_TYPE VARCHAR(50) NOT NULL,
  QT_FILE_LENGTH INTEGER UNSIGNED NOT NULL,
  IS_COMPRESSED_FILE_CONTENT BOOL NOT NULL DEFAULT true,
  QT_COMPRESSED_FILE_LENGTH INTEGER UNSIGNED NOT NULL,
  DS_COMPRESSED_FILE_INFORMATION VARCHAR(300) NOT NULL,
  TX_HASH_FILE_BYTES VARCHAR(100) NOT NULL,
  TX_HASH_FILE_CONTENT_OCR VARCHAR(100) NULL,
  IS_EXTRACTION_TEXT_OCR_FILE BOOL NOT NULL DEFAULT false,
  CD_STATUS_EXTRACTION_TEXT_ORC_FILE INTEGER UNSIGNED NOT NULL DEFAULT 0,
  DH_REGISTERED_FILE_STORAGE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DH_REMOVED_FILE_STORAGE DATETIME NULL,
  DH_BACKUP_FILE_STORAGE DATETIME NULL,
  CD_STATUS_FILE_STORAGE INTEGER UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY(ID_FILE_STORAGE),
  INDEX FK_APPLICATION_FILE(ID_APPICATION),
  FOREIGN KEY(ID_APPICATION)
    REFERENCES TB_APPICATION(ID_APPICATION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade que armazena o(s) Storage(s) em que o arquivo foi armazenado, pois será possível enviar um arquivo para mais de um storage em caso de solicitação de replicação de dados ou sincronização de estruturas.
-- ------------------------------------------------------------

CREATE TABLE TB_FILE_STORAGE_CLIENT (
  ID_FILE_STORAGE_CLIENT BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_STORAGE BIGINT NOT NULL,
  ID_SERVER_STORAGE_CLIENT VARCHAR(100) NULL,
  PRIMARY KEY(ID_FILE_STORAGE_CLIENT),
  INDEX FK_FILE_STORAGE_CLIENT(ID_FILE_STORAGE),
  FOREIGN KEY(ID_FILE_STORAGE)
    REFERENCES TB_FILE_STORAGE(ID_FILE_STORAGE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade que armazena acessos ao arquivo armazemando no file server, registrando as informações do usuário que está acessando ou token de acesso caso seja um acesso direto por token, via link.
-- ------------------------------------------------------------

CREATE TABLE TB_FILE_STORAGE_LOG_ACCESS (
  ID_FILE_STORAGE_LOG_ACCESS BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_STORAGE BIGINT NOT NULL,
  NM_USER_LOG_ACCESS VARCHAR(100) NOT NULL,
  CD_IP_USER_LOG_ACCESS VARCHAR(30) NOT NULL,
  DS_USER_AGENT_LOG_ACCESS VARCHAR(255) NOT NULL,
  DS_CHANEL_USER_LOG_ACCESS VARCHAR(20) NOT NULL,
  DH_REGISTERED_LOG_ACCESS DATETIME NOT NULL,
  PRIMARY KEY(ID_FILE_STORAGE_LOG_ACCESS),
  INDEX FK_FILE_STORAGE_LOG(ID_FILE_STORAGE),
  FOREIGN KEY(ID_FILE_STORAGE)
    REFERENCES TB_FILE_STORAGE(ID_FILE_STORAGE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade responsável por armazenar as chaves de acesso, token, para acesso de um arquivo por link direto ou QR Code (link) com verificação de validade do token.
-- ------------------------------------------------------------

CREATE TABLE TB_FILE_STORAGE_ACCESS_TOKEN (
  ID_FILE_STORAGE_ACCESS_TOKEN BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_STORAGE BIGINT NOT NULL,
  CD_FILE_STORAGE_CLIENT VARCHAR(100) NOT NULL,
  CD_ACCESS_TOKEN_FILE VARCHAR(100) NOT NULL,
  QT_TIME_EXPIRATION_TOKEN BIGINT NOT NULL DEFAULT 0,
  QT_MAXIMUM_ACCESSES_TOKEN INTEGER UNSIGNED NOT NULL DEFAULT 0,
  DH_REGISTERED_TOKEN DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DH_LAST_ACCESS_TOKEN DATETIME NULL,
  PRIMARY KEY(ID_FILE_STORAGE_ACCESS_TOKEN),
  INDEX FK_FILE_STORAGE_TOKEN(ID_FILE_STORAGE),
  FOREIGN KEY(ID_FILE_STORAGE)
    REFERENCES TB_FILE_STORAGE(ID_FILE_STORAGE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade que armazena o processo OCR do arquivo quando sinalizado na aplicação que é para realizar para os arquivos pertinentes ao processo de extração de informações via OCR.
-- ------------------------------------------------------------

CREATE TABLE TB_FILE_OCR_EXTRACTION (
  ID_FILE_OCR_EXTRACTION BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_STORAGE BIGINT NOT NULL,
  TX_CONTENT_FILE_OCR TEXT NOT NULL,
  TX_HASH_CONTENT_FILE_OCR VARCHAR(100) NOT NULL,
  NM_DOCUMENT_TYPE_FILE_OCR VARCHAR(50) NOT NULL,
  VL_DEGREE_CONFIDENCE_DOCUMENT_TYPE DECIMAL(2,2) NOT NULL DEFAULT 0.0,
  DH_REGISTERED_EXTRACTION_OCR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID_FILE_OCR_EXTRACTION),
  INDEX FK_FILE_STORAGE_OCR(ID_FILE_STORAGE),
  FOREIGN KEY(ID_FILE_STORAGE)
    REFERENCES TB_FILE_STORAGE(ID_FILE_STORAGE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade que armazena os campos (chave e valor) do processo de OCR realizado no arquivo.
-- ------------------------------------------------------------

CREATE TABLE TB_FILE_OCR_EXTRACTION_FIELDS (
  ID_FILE_OCR_EXTRACTION_FIELDS BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_OCR_EXTRACTION BIGINT NOT NULL,
  NM_FIELD_EXTRACTION VARCHAR(300) NOT NULL,
  TX_CONTENT_FIELD_EXTRACTION VARCHAR(500) NOT NULL,
  PRIMARY KEY(ID_FILE_OCR_EXTRACTION_FIELDS),
  INDEX FK_FILE_OCR_EXTRACTION(ID_FILE_OCR_EXTRACTION),
  FOREIGN KEY(ID_FILE_OCR_EXTRACTION)
    REFERENCES TB_FILE_OCR_EXTRACTION(ID_FILE_OCR_EXTRACTION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);