CREATE TABLE tb_server_storage_metrics (
  ID_SERVER_STORAGE_METRICS BIGINT NOT NULL AUTO_INCREMENT,
  QT_TOTAL_SPACE_STORAGE INTEGER UNSIGNED NOT NULL,
  QT_FREE_SPACE_STORAGE INTEGER UNSIGNED NOT NULL,
  QT_TOTAL_FILES_STORAGE INTEGER UNSIGNED NOT NULL,
  VL_RESPONSE_TIME_STORAGE INTEGER UNSIGNED NOT NULL,
  QT_REQUEST_LAST_MINUTE_STORAGE INTEGER UNSIGNED NOT NULL DEFAULT 0,
  DH_LAST_REQUEST_STORAGE DATETIME NULL,
  QT_ERRORS_LAST_REQUEST_STORAGE INTEGER UNSIGNED NOT NULL DEFAULT 0,
  DH_LAST_AVAILABLE_STORAGE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID_SERVER_STORAGE_METRICS)
);

CREATE TABLE tb_file_storage_compressed (
  ID_FILE_STORAGE_COMPRESSED BIGINT NOT NULL AUTO_INCREMENT,
  NM_COMPRESSED_FILE_FISICAL VARCHAR(100) NOT NULL,
  QT_COMPRESSED_FILE_LENGTH INTEGER UNSIGNED NOT NULL DEFAULT 0,
  DS_COMPRESSED_FILE_CONTENT_TYPE VARCHAR(100) NOT NULL,
  DS_COMPRESSED_FILE_INFORMATION VARCHAR(300) NOT NULL,
  TX_COMPRESSED_HASH_FILE_BYTES VARCHAR(100) NOT NULL,
  VL_COMPRESSED_FILE_CONTENT DECIMAL NOT NULL DEFAULT 0.0,
  PRIMARY KEY(ID_FILE_STORAGE_COMPRESSED)
);

-- ------------------------------------------------------------
-- Entidade que armazena as aplicações utilizadas no proceso de armazenamento de arquivos nos repositórios de arquivos (file server).
-- ------------------------------------------------------------

CREATE TABLE tb_application (
  ID_APPLICATION BIGINT NOT NULL AUTO_INCREMENT,
  NM_APPLICATION VARCHAR(10) NOT NULL,
  DS_APPLICATION VARCHAR(500) NOT NULL,
  TX_ALLOWED_FILE_TYPES TEXT NOT NULL,
  QT_MAXIMUM_FILE_SIZE_MB BIGINT NOT NULL DEFAULT 2,
  IS_COMPRESSED_FILE_CONTENT_TOZIP BOOL NOT NULL DEFAULT true,
  IS_CONVERT_IMAGE_FILE_TOWEBP BOOL NOT NULL DEFAULT true,
  IS_APPLY_OCR_FILE_CONTENT BOOL NOT NULL DEFAULT false,
  IS_ALLOW_DUPLICATE_FILE BOOL NOT NULL DEFAULT true,
  IS_REQUIRES_FILE_REPLICATION BOOL NOT NULL DEFAULT false,
  QT_TOTAL_FILES_APPLICATION BIGINT NOT NULL DEFAULT 0,
  CD_STATUS_APPLICATION INTEGER UNSIGNED NOT NULL DEFAULT 1,
  DH_REGISTERED_APPLICATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DH_REMOVED_APPLICATION DATETIME NULL,
  PRIMARY KEY(ID_APPLICATION),
  INDEX IX_NM_APPLICATION(NM_APPLICATION)
);

-- ------------------------------------------------------------
-- Entidade que armazena o processo OCR do arquivo quando sinalizado na aplicação que é para realizar para os arquivos pertinentes ao processo de extração de informações via OCR.
-- ------------------------------------------------------------

CREATE TABLE tb_file_ocr_extraction (
  ID_FILE_OCR_EXTRACTION BIGINT NOT NULL,
  TX_CONTENT_FILE_OCR TEXT NOT NULL,
  TX_HASH_CONTENT_FILE_OCR VARCHAR(100) NOT NULL,
  NM_DOCUMENT_TYPE_FILE_OCR VARCHAR(50) NOT NULL,
  VL_DEGREE_CONFIDENCE_DOCUMENT_TYPE DECIMAL(2,2) NOT NULL DEFAULT 0.0,
  CD_STATUS_EXTRACTION_TEXT_ORC_FILE INTEGER UNSIGNED NOT NULL DEFAULT 0,
  DH_START_EXTRACTION_OCR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DH_END_EXTRACTION_OCR DATETIME NULL,
  PRIMARY KEY(ID_FILE_OCR_EXTRACTION)
);

-- ------------------------------------------------------------
-- Entidade que armazena os Server Storage que são os Clientes (hosts) espalhados pelo rede interna e controlados pelo servidor MeshStorage, para envio dos arquivos para armazenamento.
-- ------------------------------------------------------------

CREATE TABLE tb_server_storage (
  ID_SERVER_STORAGE BIGINT NOT NULL AUTO_INCREMENT,
  ID_SERVER_STORAGE_METRICS BIGINT NOT NULL,
  ID_SERVER_STORAGE_CLIENT VARCHAR(100) NOT NULL,
  NM_SERVER_STORAGE VARCHAR(100) NOT NULL,
  NM_STORAGE_CLIENT VARCHAR(50) NOT NULL,
  CD_IP_SERVER_STORAGE VARCHAR(20) NOT NULL,
  DS_OS_SERVER_STORAGE VARCHAR(50) NOT NULL,
  CD_STATUS_SERVER_STORAGE INTEGER UNSIGNED NOT NULL,
  DH_REGISTERED_SERVER_STORAGE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DH_REMOVED_SERVER_STORAGE DATETIME NULL,
  PRIMARY KEY(ID_SERVER_STORAGE),
  INDEX IX_CD_SERVER_STORAGE(NM_SERVER_STORAGE, NM_STORAGE_CLIENT),
  INDEX IX_ID_SERVER_STORAGE_CLIENT(ID_SERVER_STORAGE_CLIENT),
  INDEX IX_CD_STATUS_SERVER_STORAGE(CD_STATUS_SERVER_STORAGE),
  INDEX IX_NM_SERVER_STORAGE(NM_SERVER_STORAGE),
  INDEX IX_ID_SERVER_STORAGE_METRICS(ID_SERVER_STORAGE_METRICS),
  FOREIGN KEY(ID_SERVER_STORAGE_METRICS)
    REFERENCES tb_server_storage_metrics(ID_SERVER_STORAGE_METRICS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade que armazena os campos (chave e valor) do processo de OCR realizado no arquivo.
-- ------------------------------------------------------------

CREATE TABLE tb_file_ocr_extraction_fields (
  ID_FILE_OCR_EXTRACTION_FIELDS BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_OCR_EXTRACTION BIGINT NOT NULL,
  NM_FIELD_EXTRACTION VARCHAR(300) NOT NULL,
  TX_CONTENT_FIELD_EXTRACTION VARCHAR(500) NOT NULL,
  PRIMARY KEY(ID_FILE_OCR_EXTRACTION_FIELDS),
  INDEX IX_ID_FILE_OCR_EXTRACTION(ID_FILE_OCR_EXTRACTION),
  FOREIGN KEY(ID_FILE_OCR_EXTRACTION)
    REFERENCES tb_file_ocr_extraction(ID_FILE_OCR_EXTRACTION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade para armazenamento das informações do arquivo armazenado no repositório de arquivos.
-- ------------------------------------------------------------

CREATE TABLE tb_file_storage (
  ID_FILE_STORAGE BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_OCR_EXTRACTION BIGINT NULL,
  ID_FILE_STORAGE_COMPRESSED BIGINT NULL,
  ID_APPLICATION BIGINT NOT NULL,
  CD_FILE_STORAGE_CLIENT VARCHAR(100) NOT NULL,
  DS_APPLICATION_STORAGE_FOLDER VARCHAR(100) NOT NULL,
  NM_FILE_LOGIC VARCHAR(300) NOT NULL,
  NM_FILE_FISICAL VARCHAR(100) NOT NULL,
  DS_FILE_CONTENT_TYPE VARCHAR(100) NOT NULL,
  QT_FILE_LENGTH INTEGER UNSIGNED NOT NULL,
  TX_HASH_FILE_BYTES VARCHAR(100) NOT NULL,
  IS_COMPRESSED_FILE_CONTENT BOOL NOT NULL DEFAULT false,
  IS_EXTRACTION_TEXT_OCR_FILE BOOL NOT NULL DEFAULT false,
  CD_STATUS_FILE_STORAGE INTEGER UNSIGNED NOT NULL DEFAULT 1,
  DH_REGISTERED_FILE_STORAGE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DH_REMOVED_FILE_STORAGE DATETIME NULL,
  DH_BACKUP_FILE_STORAGE DATETIME NULL,
  PRIMARY KEY(ID_FILE_STORAGE),
  INDEX IX_CD_FILE_STORAGE_CLIENT(CD_FILE_STORAGE_CLIENT),
  INDEX IX_ID_APPLICATION_HASH_FILE_BYTES(TX_HASH_FILE_BYTES),
  INDEX IX_ID_APPLICATION(ID_APPLICATION),
  INDEX IX_ID_FILE_STORAGE_COMPRESSED(ID_FILE_STORAGE_COMPRESSED),
  INDEX IX_ID_FILE_OCR_EXTRACTION(ID_FILE_OCR_EXTRACTION),
  FOREIGN KEY(ID_APPLICATION)
    REFERENCES tb_application(ID_APPLICATION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_FILE_STORAGE_COMPRESSED)
    REFERENCES tb_file_storage_compressed(ID_FILE_STORAGE_COMPRESSED)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_FILE_OCR_EXTRACTION)
    REFERENCES tb_file_ocr_extraction(ID_FILE_OCR_EXTRACTION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade que armazena acessos ao arquivo armazemando no file server, registrando as informações do usuário que está acessando ou token de acesso caso seja um acesso direto por token, via link.
-- ------------------------------------------------------------

CREATE TABLE tb_file_storage_log_access (
  ID_FILE_STORAGE_LOG_ACCESS BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_STORAGE BIGINT NOT NULL,
  NM_USER_LOG_ACCESS VARCHAR(100) NOT NULL,
  CD_IP_USER_LOG_ACCESS VARCHAR(30) NOT NULL,
  DS_USER_AGENT_LOG_ACCESS VARCHAR(255) NOT NULL,
  DS_CHANEL_USER_LOG_ACCESS VARCHAR(20) NOT NULL,
  DH_REGISTERED_LOG_ACCESS DATETIME NOT NULL,
  PRIMARY KEY(ID_FILE_STORAGE_LOG_ACCESS),
  INDEX IX_ID_FILE_STORAGE(ID_FILE_STORAGE),
  INDEX IX_NM_USER_LOG_ACCESS(NM_USER_LOG_ACCESS),
  FOREIGN KEY(ID_FILE_STORAGE)
    REFERENCES tb_file_storage(ID_FILE_STORAGE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade responsável por armazenar as chaves de acesso, token, para acesso de um arquivo por link direto ou QR Code (link) com verificação de validade do token.
-- ------------------------------------------------------------

CREATE TABLE tb_file_storage_access_token (
  ID_FILE_STORAGE_ACCESS_TOKEN BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_STORAGE BIGINT NOT NULL,
  CD_FILE_STORAGE_CLIENT VARCHAR(100) NOT NULL,
  CD_ACCESS_TOKEN_FILE VARCHAR(100) NOT NULL,
  QT_TIME_EXPIRATION_TOKEN BIGINT NOT NULL DEFAULT 0,
  QT_MAXIMUM_ACCESSES_TOKEN INTEGER UNSIGNED NOT NULL DEFAULT 0,
  DH_REGISTERED_TOKEN DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DH_LAST_ACCESS_TOKEN DATETIME NULL,
  PRIMARY KEY(ID_FILE_STORAGE_ACCESS_TOKEN),
  INDEX IX_ID_FILE_STORAGE(ID_FILE_STORAGE),
  INDEX IX_CD_ACCESS_TOKEN_FILE(CD_ACCESS_TOKEN_FILE),
  FOREIGN KEY(ID_FILE_STORAGE)
    REFERENCES tb_file_storage(ID_FILE_STORAGE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- ------------------------------------------------------------
-- Entidade que armazena o(s) Storage(s) em que o arquivo foi armazenado, pois será possível enviar um arquivo para mais de um storage em caso de solicitação de replicação de dados ou sincronização de estruturas.
-- ------------------------------------------------------------

CREATE TABLE tb_file_storage_client (
  ID_FILE_STORAGE_CLIENT BIGINT NOT NULL AUTO_INCREMENT,
  ID_FILE_STORAGE BIGINT NOT NULL,
  ID_SERVER_STORAGE_CLIENT VARCHAR(100) NULL,
  PRIMARY KEY(ID_FILE_STORAGE_CLIENT),
  INDEX IX_ID_FILE_STORAGE(ID_FILE_STORAGE),
  FOREIGN KEY(ID_FILE_STORAGE)
    REFERENCES tb_file_storage(ID_FILE_STORAGE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


